### ISSUE TITLE
Allow users to disable the feature temporally 

### ISSUE THREAD

**Issue by rebornix** [extr0py/vscode-relative-line-numbers#4]
Currently I'm not sure whether we have access to the breakpoints information so a workaround for now is allowing users to disable this feature temporally so they can set breakpoints perfectly.

**Comment by xconverge** [comment]
Yea will definitely be cool if you can just not draw if there is a breakpoint etc.

I would open an issue with vscode and see if there is a way to get breakpoint info or something for now...

**Comment by rebornix** [comment]
@xconverge we are even thinking about supporting multiple layers for the gutter, which makes the gutter more customizable.

**Comment by xconverge** [comment]
Do you think there will be a way to set gutter width/font color etc?

when using this extension with a huge file with >1000 lines, the numbering starts to get crazy

**Comment by rebornix** [comment]
AFAIK, currently we don't have any other support :( But this extension does inspire me and I'll make sure we have progress with the Gutter customization. It's also useful for Git Blame.

**Comment by extr0py** [comment]
It would be awesome to extend the line numbering somehow. Or have the relative numbers as a setting like in this fork: https://github.com/alfanick/vscode/. But either way, having more gutter support would be great - thanks for pushing for it!

**Comment by extr0py** [comment]
In the meantime, I'll add a command to enable / disable. I was hoping there was an event or info I could check to see if VSCode was in debugging mode, but I didn't see anything.

**Comment by extr0py** [comment]
Added enable / disable commands for this plugin. Thanks for all the details, @rebornix !

**Comment by rebornix** [comment]
Thanks for the update and the reference to the fork which implements relative line number! I'll check its status and see if we can merge it into our code base!
