### ISSUE TITLE
Relative line numbers bump up against actual line numbers

### ISSUE THREAD

**Issue by jeffschwartz** [extr0py/vscode-relative-line-numbers#6]
v0.0.4

![screen shot 2016-09-13 at 8 24 41 pm](https://cloud.githubusercontent.com/assets/271288/18496058/9b609c06-79f0-11e6-8367-3c0edf29ff69.png)

**Comment by Ravencrow** [comment]
You can disable the line number to keep only the relative number. I did it and it works.

**Comment by pbdm** [comment]
sometimes we need both these two numbers, I think it's better to change style if we can

**Comment by bryphe** [comment]
This is deprecated now with the `editor.lineNumbers` setting with a value of `relative`. Please use that setting instead of this plugin, it will be a better experience.
