### ISSUE TITLE
Relative line number will cover up debug breakpoints.

### ISSUE THREAD

**Issue by zuoxiaofeng** [extr0py/vscode-relative-line-numbers#8]
![image](https://user-images.githubusercontent.com/9400125/42357920-c815b680-810c-11e8-80d5-397c446c68d9.png)

For example: I have setup 4 breakpoints on line 3, 4, 5, 6, but only breakpoint on current line is display, other are covered up by the relative line number.

**Comment by neckutrek** [comment]
Any updates on this? Any ideas for a solution?

**Comment by zuoxiaofeng** [comment]
> Any updates on this? Any ideas for a solution?

Vscode officially support relative line now and without this issue. 

"editor.lineNumbers": "relative"
